var searchData=
[
  ['rasterizer',['Rasterizer',['../class_rasterizer.html',1,'']]],
  ['rasterizercache',['RasterizerCache',['../class_rasterizer_cache.html',1,'']]],
  ['rasterizerregs',['RasterizerRegs',['../struct_pica_1_1_rasterizer_regs.html',1,'Pica']]],
  ['rasterizerregs_2e_5f_5funnamed_5f_5f',['RasterizerRegs.__unnamed__',['../namespace_pica.html#union_pica_1_1_rasterizer_regs_8____unnamed____',1,'Pica']]],
  ['rasterizerregs_2escissor_5ftest',['RasterizerRegs.scissor_test',['../namespace_pica.html#struct_pica_1_1_rasterizer_regs_8scissor__test',1,'Pica']]],
  ['rasterizerregs_2escissor_5ftest_2e_5f_5funnamed_5f_5f',['RasterizerRegs.scissor_test.__unnamed__',['../namespace_pica.html#union_pica_1_1_rasterizer_regs_8scissor__test_8____unnamed____',1,'Pica::RasterizerRegs.scissor_test.__unnamed__'],['../namespace_pica.html#union_pica_1_1_rasterizer_regs_8scissor__test_8____unnamed____',1,'Pica::RasterizerRegs.scissor_test.__unnamed__']]],
  ['rasterizerregs_2eviewport_5fcorner',['RasterizerRegs.viewport_corner',['../namespace_pica.html#union_pica_1_1_rasterizer_regs_8viewport__corner',1,'Pica']]],
  ['rectangle',['Rectangle',['../struct_math_util_1_1_rectangle.html',1,'MathUtil']]],
  ['rectangle_3c_20float_20_3e',['Rectangle&lt; float &gt;',['../struct_math_util_1_1_rectangle.html',1,'MathUtil']]],
  ['rectangle_3c_20unsigned_20_3e',['Rectangle&lt; unsigned &gt;',['../struct_math_util_1_1_rectangle.html',1,'MathUtil']]],
  ['ref',['Ref',['../class_common_1_1_bit_set_1_1_ref.html',1,'Common::BitSet']]],
  ['registers',['Registers',['../struct_pica_1_1_shader_1_1_unit_state.html#struct_pica_1_1_shader_1_1_unit_state_1_1_registers',1,'Pica::Shader::UnitState']]],
  ['regs',['Regs',['../struct_l_c_d_1_1_regs.html',1,'LCD::Regs'],['../struct_g_p_u_1_1_regs.html',1,'GPU::Regs'],['../struct_pica_1_1_regs.html',1,'Pica::Regs']]],
  ['regs_2e_5f_5funnamed_5f_5f',['Regs.__unnamed__',['../namespace_pica.html#union_pica_1_1_regs_8____unnamed____',1,'Pica']]],
  ['regs_2e_5f_5funnamed_5f_5f_2e_5f_5funnamed_5f_5f',['Regs.__unnamed__.__unnamed__',['../namespace_pica.html#struct_pica_1_1_regs_8____unnamed_____8____unnamed____',1,'Pica']]],
  ['regs_2ecommand_5fprocessor_5fconfig',['Regs.command_processor_config',['../namespace_g_p_u.html#struct_g_p_u_1_1_regs_8command__processor__config',1,'GPU']]],
  ['relocationentry',['RelocationEntry',['../struct_service_1_1_l_d_r_1_1_c_r_o_helper_1_1_relocation_entry.html',1,'Service::LDR::CROHelper']]],
  ['renderer',['Renderer',['../class_renderer.html',1,'']]],
  ['requesthelperbase',['RequestHelperBase',['../class_i_p_c_1_1_request_helper_base.html',1,'IPC']]],
  ['requestparser',['RequestParser',['../class_i_p_c_1_1_request_parser.html',1,'IPC']]],
  ['resolution',['Resolution',['../namespace_service_1_1_c_a_m.html#struct_service_1_1_c_a_m_1_1_resolution',1,'Service::CAM']]],
  ['resourcelimit',['ResourceLimit',['../class_kernel_1_1_resource_limit.html',1,'Kernel']]],
  ['responsebuilder',['ResponseBuilder',['../class_i_p_c_1_1_response_builder.html',1,'IPC']]],
  ['resultcode',['ResultCode',['../union_result_code.html',1,'']]],
  ['results',['Results',['../class_core_1_1_perf_stats.html#struct_core_1_1_perf_stats_1_1_results',1,'Core::PerfStats']]],
  ['resultval',['ResultVal',['../class_result_val.html',1,'']]],
  ['reverbeffect',['ReverbEffect',['../struct_audio_core_1_1_h_l_e_1_1_dsp_configuration_1_1_reverb_effect.html',1,'AudioCore::HLE::DspConfiguration']]],
  ['ringbuffer',['RingBuffer',['../class_common_1_1_ring_buffer.html',1,'Common']]],
  ['ringbuffer_3c_20s16_2c_200x2000_2c_202_20_3e',['RingBuffer&lt; s16, 0x2000, 2 &gt;',['../class_common_1_1_ring_buffer.html',1,'Common']]],
  ['ro',['RO',['../class_service_1_1_l_d_r_1_1_r_o.html',1,'Service::LDR']]],
  ['romfsdelaygenerator',['RomFSDelayGenerator',['../class_file_sys_1_1_rom_f_s_delay_generator.html',1,'FileSys']]],
  ['romfsfile',['RomFSFile',['../class_rom_f_s_1_1_rom_f_s_file.html',1,'RomFS']]],
  ['romfsreader',['RomFSReader',['../class_file_sys_1_1_rom_f_s_reader.html',1,'FileSys']]],
  ['room',['Room',['../class_network_1_1_room.html',1,'Network']]],
  ['roomimpl',['RoomImpl',['../class_network_1_1_room_1_1_room_impl.html',1,'Network::Room']]],
  ['roommember',['RoomMember',['../class_network_1_1_room_member.html',1,'Network']]],
  ['roommemberimpl',['RoomMemberImpl',['../class_network_1_1_room_member_1_1_room_member_impl.html',1,'Network::RoomMember']]],
  ['rpcserver',['RPCServer',['../class_r_p_c_1_1_r_p_c_server.html',1,'RPC']]],
  ['rtc',['RTC',['../class_service_1_1_m_c_u_1_1_r_t_c.html',1,'Service::MCU']]]
];
