var namespace_kernel =
[
    [ "AddressArbiter", "class_kernel_1_1_address_arbiter.html", "class_kernel_1_1_address_arbiter" ],
    [ "AddressMapping", "namespace_kernel.html#struct_kernel_1_1_address_mapping", "namespace_kernel_struct_kernel_1_1_address_mapping_dup" ],
    [ "ClientPort", "class_kernel_1_1_client_port.html", "class_kernel_1_1_client_port" ],
    [ "ClientSession", "class_kernel_1_1_client_session.html", "class_kernel_1_1_client_session" ],
    [ "CodeSet", "struct_kernel_1_1_code_set.html", "struct_kernel_1_1_code_set" ],
    [ "Event", "class_kernel_1_1_event.html", "class_kernel_1_1_event" ],
    [ "HandleTable", "class_kernel_1_1_handle_table.html", "class_kernel_1_1_handle_table" ],
    [ "HLERequestContext", "class_kernel_1_1_h_l_e_request_context.html", "class_kernel_1_1_h_l_e_request_context" ],
    [ "MappedBuffer", "class_kernel_1_1_mapped_buffer.html", "class_kernel_1_1_mapped_buffer" ],
    [ "MemoryInfo", "namespace_kernel.html#struct_kernel_1_1_memory_info", "namespace_kernel_struct_kernel_1_1_memory_info_dup" ],
    [ "MemoryRegionInfo", "namespace_kernel.html#struct_kernel_1_1_memory_region_info", "namespace_kernel_struct_kernel_1_1_memory_region_info_dup" ],
    [ "Mutex", "class_kernel_1_1_mutex.html", "class_kernel_1_1_mutex" ],
    [ "Object", "class_kernel_1_1_object.html", "class_kernel_1_1_object" ],
    [ "PageInfo", "namespace_kernel.html#struct_kernel_1_1_page_info", "namespace_kernel_struct_kernel_1_1_page_info_dup" ],
    [ "Process", "class_kernel_1_1_process.html", "class_kernel_1_1_process" ],
    [ "ProcessFlags", "namespace_kernel.html#union_kernel_1_1_process_flags", "namespace_kernel_union_kernel_1_1_process_flags_dup" ],
    [ "ResourceLimit", "class_kernel_1_1_resource_limit.html", "class_kernel_1_1_resource_limit" ],
    [ "Semaphore", "class_kernel_1_1_semaphore.html", "class_kernel_1_1_semaphore" ],
    [ "ServerPort", "class_kernel_1_1_server_port.html", "class_kernel_1_1_server_port" ],
    [ "ServerSession", "class_kernel_1_1_server_session.html", "class_kernel_1_1_server_session" ],
    [ "Session", "namespace_kernel.html#class_kernel_1_1_session", "namespace_kernel_class_kernel_1_1_session_dup" ],
    [ "SessionRequestHandler", "class_kernel_1_1_session_request_handler.html", "class_kernel_1_1_session_request_handler" ],
    [ "SharedMemory", "class_kernel_1_1_shared_memory.html", "class_kernel_1_1_shared_memory" ],
    [ "Thread", "class_kernel_1_1_thread.html", "class_kernel_1_1_thread" ],
    [ "Timer", "class_kernel_1_1_timer.html", "class_kernel_1_1_timer" ],
    [ "VirtualMemoryArea", "struct_kernel_1_1_virtual_memory_area.html", "struct_kernel_1_1_virtual_memory_area" ],
    [ "VMManager", "class_kernel_1_1_v_m_manager.html", "class_kernel_1_1_v_m_manager" ],
    [ "WaitObject", "class_kernel_1_1_wait_object.html", "class_kernel_1_1_wait_object" ]
];