var namespace_input_common_1_1_cemuhook_u_d_p_1_1_response =
[
    [ "PadData", "namespace_input_common_1_1_cemuhook_u_d_p_1_1_response.html#struct_input_common_1_1_cemuhook_u_d_p_1_1_response_1_1_pad_data", "namespace_input_common_1_1_cemuhook_u_d_p_1_1_response_struct_input_common_1_1_cemuhook_u_d_p_1_1_response_1_1_pad_data_dup" ],
    [ "PortInfo", "namespace_input_common_1_1_cemuhook_u_d_p_1_1_response.html#struct_input_common_1_1_cemuhook_u_d_p_1_1_response_1_1_port_info", "namespace_input_common_1_1_cemuhook_u_d_p_1_1_response_struct_input_common_1_1_cemuhook_u_d_p_1_1_response_1_1_port_info_dup" ],
    [ "Version", "namespace_input_common_1_1_cemuhook_u_d_p_1_1_response.html#struct_input_common_1_1_cemuhook_u_d_p_1_1_response_1_1_version", "namespace_input_common_1_1_cemuhook_u_d_p_1_1_response_struct_input_common_1_1_cemuhook_u_d_p_1_1_response_1_1_version_dup" ]
];